### ISSUE TITLE
Generate the concept for a sharable wiki / web pages

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#104]
Generate the concept for a sharable wiki / web pages
- Synchronizable and sharable wiki pages shall be part of qaul.net.
- They shall be visible for every one in the network.
- They shall be editable (locally and remote)
- They shall be sharable among users and be stored locally, with the possibility
  of synchronization but also differation (similar to a git repository)
- They shall be able to contain media objects, such as images & videos.

**Comment by jaromil** [comment]
How about running gobby?
https://gobby.github.io/

**Comment by jaromil** [comment]
or build something with their https://github.com/gobby/libinfinity

**Comment by deavmi** [comment]
Yeah, just run a service. And it should be available on your IP at a given port on the mesh.

**Comment by MathJud** [comment]
libinifity looks really interesting, but I think we should create an entirely decentralized solution.

**Comment by deavmi** [comment]
I truly am all about just the mesh. I believe people should decide **what** services run on the mesh and **how**. My humble opinion.

**Comment by deavmi** [comment]
What is libinfinity?

**Comment by MathJud** [comment]
@deavmi check link in jaromil's post to libinfinity  https://github.com/gobby/libinfinity

**Comment by deavmi** [comment]
I see. I guess Etherpad would have some similiar system.

**Comment by jaromil** [comment]
I generally agree with @deavmi on his stance to focus on the mesh. If you keep it simple and on the low layer, it will all keep more maintainable and leave you more time to work on details, while leaving people the freedom to run any stuff on application space. Its a good mantra for the programmer, to not build-in features, but leave space for inter-operability. Also process separation helps stability.

**Comment by deavmi** [comment]
Good words in last comment
