### ISSUE TITLE
kill all qaul related processes when qaul is killed

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#109]
At the moment their are independent processes (olsrd, portfw) that are killed when quitting qaul-gtk via GUI. When qaul-gtk is killed the independent processes keep running. 
This is unwanted behaviour. 

enhancement:
The independent processes should be child processes which are killed automatically when qaul-gtk is killed.

**Comment by deavmi** [comment]
> The independent processes should be child processes which are killed automatically when qaul-gtk is killed.

Sounds good to me. I think you should do that.

**Comment by deavmi** [comment]
Obviously don't force a quit but let them shutdown gracefully.
