### ISSUE TITLE
iOS version?

### ISSUE THREAD

**Issue by deavmi** [qaul/qaul.net#117]
Is the iOS version no longer supported?

**Comment by CryptoCore-Collective** [comment]
I was so excited to find qaul until I saw no iOS support.

**Comment by deavmi** [comment]
There is an iOS version.

If you are jailbroken.

On 21 May 2018 17:01:09 SAST, CryptoCore-Collective <notifications@github.com> wrote:
>I was so excited to find qaul until I saw no iOS support.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/qaul/qaul.net/issues/117#issuecomment-390680940

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by spacekookie** [comment]
The way that qaul.net currently implements network routing unfortunately requires kernel space access to routing tables. On Android this means that the device needs to be rooted (to get access to the routing tables as well as provide a custom driver for adhoc wifi support.

On iOS that means that you need to jailbreak your device.

Generally the core library is being refactored a lot right now, meaning that hopefully soon we will be able to not require root anymore at which point support iOS will also become easier again.

**Comment by deavmi** [comment]
Oh damn . Nice.
