### ISSUE TITLE
Add IPv6 support

### ISSUE THREAD

**Issue by deavmi** [qaul/qaul.net#127]
Could you add IPv6 support?

**Comment by MathJud** [comment]
IPv6 would be great! Needs some work in qaullib though.

**Comment by deavmi** [comment]
OOOh okay.

**Comment by deavmi** [comment]
Also a feature to choose whether you want to use both or only IPv4 or IPv6.

**Comment by deavmi** [comment]
I wanted to know, how do the devices get their IPs. Is it completely decentralized because I think you said they used random numbers which in that case is completely decentralized as no DHCP is being used?

**Comment by MathJud** [comment]
@deavmi you're right!

**Comment by deavmi** [comment]
Yay. :+1:
