### ISSUE TITLE
Latest Windows Build: Problems

### ISSUE THREAD

**Issue by deavmi** [qaul/qaul.net#130]
Latest build for Windows seems to have many problems:
- Cannot send messages to the public.
- Doesn't list users on the network (Qaul area of the network)
- Calling doesn't work when I call my Windows PC from my Linux PC (it rings once on the Windows machine but the screen doesn't change to the incoming call page) - Linux machine just shows calling screen with loading bar saying "Connecting" and just stays there for a while and then says "Call ended" and if I try call again then it doesn't even ring on the Windows machine.

**Comment by deavmi** [comment]
@MathJud Was anything in the backend recently updated, like Windows seems badly affected?

**Comment by MathJud** [comment]
Yes, the internal web server was updated. I have to look into that.

**Comment by deavmi** [comment]
Oh okay. Is it Mongoose?
