### ISSUE TITLE
Question+Suggestion: Sharing of Internet connection

### ISSUE THREAD

**Issue by deavmi** [qaul/qaul.net#145]
Does the sharing of the Internet connection share the network that the chosen interface is connected to hence giving access to that network? If so, (which i think it does), then a warning message should be added on the "Share Internet conneciton" page.

**Comment by MathJud** [comment]
Yes, if your device is connected via another network to the Internet, it is possible to access this network too.
Good Point! We should add this to the documentation.

**Comment by deavmi** [comment]
Awesome, dankie baie.
