### ISSUE TITLE
Suggestion:

### ISSUE THREAD

**Issue by deavmi** [qaul/qaul.net#146]
If the user goes to the "Change language" page and selects the same language that is being used and hits okay then don't say "Qaul.net must be restarted.".

**Comment by MathJud** [comment]
OK! Thanks for the hint.
There will be a new user management with the new crypto system which is written at the moment by spacekookie as a Google summer of code project.

**Comment by deavmi** [comment]
Oh. Awesome. Public key crypto I suppose, that sounds good.

**Comment by deavmi** [comment]
See if you can actually run the crypto over olsr. Sure there is a plugin for that. As full network encryption would be nice.
