### ISSUE TITLE
Add GUI path configuration option

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#150]
The path to the GUI is hard coded in qaul.net.
The path should be configurable for the following reasons:
- to not to have to install the interface every time something has changed during the GUI development
- to allow the user to use alternative home-folder located GUI's

**Comment by deavmi** [comment]
What do you mean by this? How is the path to the GUI hard-coded? What the `qaul-gtk`?

**Comment by MathJud** [comment]
qaullib locates the GUI path automatically within the path that set in the Qaullib_Init function which is invoked by the client. It should get the path from the config table of the data base.

**Comment by deavmi** [comment]
Ever thought of switching to a config file for some aspects of the qaul.net system? I'd love this.

The database system is good for large data or multiple pieces of data being stored.
