### ISSUE TITLE
Create user store API

### ISSUE THREAD

**Issue by spacekookie** [qaul/qaul.net#177]
Define an API that will be used to interact with the user store, creating an abstraction layer around the active user store (hash tables) and the all-known-store (database)

```
 [    API    ]  <--> [ USER STORE ]
       ^
       |
       |
       v
 [   CRYPTO  ]  <--> [ KEY STORE ]


 - The API has access to the USER STORE to lookup IPs, names 
      and fingerprints with other indices

 - The CRYPTO module has access to the KEY STORE to lookup 
      public keys against fingerprints if asked

 - The KEY STORE manages public keys for remote users (not us)
      as well as private keys for different local identities

```

The user store can either be an "object-oriented" API (allocating a struct which is then used to convey context and required in every operation

```C
typedef struct qluser_store_ctx {
  // ...
} store_ctx;
int qluser_store_init(store_ctx *store, const char *db_path);
```

or as a static API where the only context is held internally as a static field

```C
// In the .c file
struct {
  // ...
} store_ctx;

static store_ctx store;

int qluser_store_init(const char *db_path) 
{
  // ...
}
```

## User store functions

When it comes to what functions to expose, the list isn't actually that long. The big question to answer is when a user should be made "persistent" (stored in the sqlite database) and when a user should only exist in the current session, being lost on restart. Is it even desirable to not keep users as persistent? Or do we want to permanently remember every user we meet? Alternatively we could only store persistent users that a local identity has marked as `trusted`. Thoughts?

  - add_user (username, fingerprint, ip)
  - get_user
    - with username
    - with fingerprint
    - with ip
    - with ?
  - delete_user
    - with username
    - with fingerprint
    - with ip
    - with ?
  - change_user (utility function which removes a user from all n tables and re-inserts it with new data)

**Comment by MathJud** [comment]
# General Concept
We should separate network view from user store, with the possibility to map multiple users to the same Network node.


# User Store
I would prefer a user store internal structure, as it could be more dynamic.
We should only have some very basic information as static fields.
While we should be able to find the user entry via IP and fingerprint (maybe even via username), user edits (delte, change, etc.) could be done only via fingerprint.

e.g.
* Fingerprint
* Username
* additional fields:
  * public key
  * trust fields


# Network structure
The network structure should be extendable to multiple network systems.
The first system to implement should be the IPv4 network (which is used in the IBSS olsrd network).

To be able to interconnect the same node over different networks, we should maybe think about giving the node an ID to which is independent of the IP address.

**Comment by spacekookie** [comment]
Right now, a user is mapped to a network node which is defined as follows

```C
/** Holds data about a node */
typedef struct qluser_node_t {
    union olsr_ip_addr  *ip;
    // ...
} qluser_node_t;
```

We probably want to create an abstraction so there is no direct mention of olsr outside of any code that specifically uses olsr. But that's how it works for now. Multiple users can be on the same node and you can also quickly find all users that use a specific IP address
