### ISSUE TITLE
files 

### ISSUE THREAD

**Issue by santhoshnp** [qaul/qaul.net#217]
I have uploaded the file but where i have to see the uploaded files

**Comment by MathJud** [comment]
I guess you are talking about the qaul.net file sharing option, right?
You should see the file under the file tab of the sharing user.
You can browse and download other users files by selecting them in the user tab.
Whenever you add a file to the file sharing, it gets advertised in the network via messaging and all users in the network receive a message about new file and can download/add it to their files.

**Comment by santhoshnp** [comment]
first off thank for you reply 
i have tried my level best but there is no file under file tab

**Comment by santhoshnp** [comment]
![screenshot 76](https://user-images.githubusercontent.com/39831264/45867922-2224f880-bda2-11e8-9bf1-4c33a749839d.png)
![screenshot 77](https://user-images.githubusercontent.com/39831264/45867923-2224f880-bda2-11e8-8f0c-3c3fefba0160.png)

**Comment by MathJud** [comment]
OK. I see you are using the qaul web interface on a windows computer.
On what system is qaul.net running?

**Comment by santhoshnp** [comment]
raspberry pi
