### ISSUE TITLE
Packaging in Guix

### ISSUE THREAD

**Issue by swedebugia** [qaul/qaul.net#218]
Hi. 
Are the gnu/linux parts stable?
Could you create a release stating if it works as expected?
Thanks!

**Comment by spacekookie** [comment]
> Could you create a release stating if it works as expected?

Hey there, what do you mean by release in this case? A github tag/release?

**Comment by swedebugia** [comment]
Yes, something to refer to. Right now the latest tag was 2 years ago. 
If I package the latest commit of the qual-ng branch, will it build and work?

**Comment by spacekookie** [comment]
I think the `qaul-ng` state is stable and works. I vaguely remember there being an effort to backport some features to it or something. Maybe we should do a current tag on that branch to include those changes.

cc/ @MathJud for more info :)

**Comment by spacekookie** [comment]
FYI we've pinned the last stable version to `release-1.0.0` which _should_ build. Maybe try that if you want to build a package
