### ISSUE TITLE
Image generation for routers

### ISSUE THREAD

**Issue by swedebugia** [qaul/qaul.net#219]
Hi. 
Have you looked at Guix and specifically the "guix system disk-image" commands? (http://guix.info/manual/en/Building-the-Installation-Image.html#Building-the-Installation-Image)
Having qual-ng in Guix would enable you to easily compose a reproducible OS-image with the packages you want with a single command and a specification.

Cheers

**Comment by spacekookie** [comment]
Hey there!

I don't think any of us have looked at Guix in any detail yet. Personally I use Nix and NixOS on some systems and I've been told that Guix has a similar approach to packaging (just with Scheme).

Not sure when we'll get around to be able to do this but it'd be cool to have. And PRs are always welcome.
