### ISSUE TITLE
Create dummy message to check whether libqaul is still alive

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#298]
A RPC dummy message shall 

- [ ] create a new debug.proto file for all kind of (future) debug messaging.
  * use the already existing DEBUG module for it https://github.com/qaul/qaul.net/blob/60d02d995bbd78747a931439c917b470e824e752/rust/libqaul/src/rpc/qaul_rpc.proto#L36
  * create a request message
  * create reply message
  * create a `panic` message ( to be used for panicking, see functionality below )
- [ ] create a debug module in libqaul
  * create file `debug.rs` in the RPC module https://github.com/qaul/qaul.net/tree/main/rust/libqaul/src/rpc
- [ ] invoke the debug module from RPC on incoming debug messages
  - [ ] transfer panic functionality to new debug module https://github.com/qaul/qaul.net/blob/60d02d995bbd78747a931439c917b470e824e752/rust/libqaul/src/rpc/mod.rs#L164
- [ ] send a test debug message from qaul-cli and print an answer on the receiving of the message.

**Comment by GildedHonour** [comment]
Similar to "heartbeat"  -- no need for any internal fields.

HeartbeatRequest and HeartbeatReply.

**Comment by GildedHonour** [comment]
Is there any simple example in the code of how UI requests some data, via protobuffers, from the lib? Which I'll then reuse here.

**Comment by MathJud** [comment]
An example on how these messages are handled can be found in the users table:

* Send a message to the GUI:
  * https://github.com/qaul/qaul.net/blob/811ed9c2707e00ab8cbe6017eb07219e163854d7/rust/libqaul/src/router/users.rs#L189
* Processing incoming messages from GUI:
  * https://github.com/qaul/qaul.net/blob/811ed9c2707e00ab8cbe6017eb07219e163854d7/rust/libqaul/src/router/users.rs#L156
* The Protobuf file: 
  * The Protobuf definition file [users.proto](https://github.com/qaul/qaul.net/blob/main/rust/libqaul/src/router/users.proto)
  * The automatically generated rust protobuf file [qaul.rpc.users.rs](https://github.com/qaul/qaul.net/blob/main/rust/libqaul/src/router/qaul.rpc.users.rs)

To send a message, send it to the RPC `send_message` function
https://github.com/qaul/qaul.net/blob/811ed9c2707e00ab8cbe6017eb07219e163854d7/rust/libqaul/src/rpc/mod.rs#L189

The messages are received through `process_received_message` function in RPC
https://github.com/qaul/qaul.net/blob/811ed9c2707e00ab8cbe6017eb07219e163854d7/rust/libqaul/src/rpc/mod.rs#L128

**Comment by GildedHonour** [comment]
Questions:

(1) GUI will always send `Request` (initiator), and Libqaul will reply with `Reply` (receiver). Never vise versa. Correct? 

(2) All the examples above are about Libqaul. What about GUI: how to send a message from GUI and process a reply in GUI?

(3) Protobuf messages will be sent in a loop, every N seconds? How, is there a similar example?

(4) How can Libqaul become non alive? In what sense non alive?

**Comment by MathJud** [comment]
Answers:

1) yes, the GUI will request something from libqaul and libqaul provides it in the response.
2) To see how this is done, you can have a look at the qaul-cli client. It communicates with libqaul via these protobuf messages. The RPC protobuf message sending and receiving is here: https://github.com/qaul/qaul.net/blob/main/rust/clients/cli/src/rpc.rs
3) The messages are scheduled in libqaul and then polled by the UI. In qaul-cli this is done in the main loop: https://github.com/qaul/qaul.net/blob/811ed9c2707e00ab8cbe6017eb07219e163854d7/rust/clients/cli/src/main.rs#L89
4) The problem was, that libqaul panicked. So it was crashed and totally unavailable. Although the main flutter application was still running.
