### ISSUE TITLE
Build Android app for iranian protests

### ISSUE THREAD

**Issue by cinorid** [qaul/qaul.net#410]
Hi
Is this application at a stage where it can be built and used by protesters? Because the internet is cut off in Iran and there is a great need for such applications.

**Comment by Cinorid** [comment]
Is it possible to provide an approximate time for the release of the application?

**Comment by cinorid** [comment]
@MathJud 
Is it possible to provide an approximate time for the release of the application?

**Comment by MathJud** [comment]
Yes, we are preparing a pre-release at the moment.
Should become available latest by tomorrow.

**Comment by cinorid** [comment]
@MathJud Thanks for your support 💗
