### ISSUE TITLE
Memory Consumption

### ISSUE THREAD

**Issue by cinorid** [qaul/qaul.net#420]
The amount of RAM usage is constantly increasing.
[screen-recorder-sat-oct-01-2022-12-45-58.webm](https://user-images.githubusercontent.com/10947730/193402397-4b866109-637e-4fda-b97c-cf1495b236df.webm)

Platform: Window 10 21H1
Versions: Flutter - v2.0.0-beta.2+744 (https://github.com/qaul/qaul.net/releases/tag/v2.0.0-beta.2%2B744-flutter)

**Comment by MathJud** [comment]
Thanks for reporting that.
we need to look into it further.

There are many things kept in memory (routing table, last tasks etc.). Also the data base is keeping stuff in memory and deciding itself when to free it and get it again from disk.

However, it is always good to have a controlling eye on the memory!

**Comment by cinorid** [comment]
@MathJud 
After 2 hours, the amount of memory used reached 3 GB.
![image](https://user-images.githubusercontent.com/10947730/193407584-3d6ddc97-c30a-410f-88d5-8722a389ad1e.png)

**Comment by MathJud** [comment]
# Bug Tracking

## TODO

- [x] Libqaul: Test Libqaul for Memory Consumption
  - Libaul was tested and no memory increase was found
- [ ] Test Flutter contiues RPC Communication
  - [ ] Users List
  - [ ] Group List
  - [ ] Group Invited
  - [ ] Chat Conversation
  - [ ] Feed List

**Comment by MathJud** [comment]
We fixed a memory leak in the FFI, which was only affecting desktop versions.
There is still a memory & CPU increase, but a slower one than before.
We are looking into that at the moment.

**Comment by MathJud** [comment]
The latest build should fix all issues.

Please make sure to manually delete the following configuration folder:
AppData\Roaming\qaul in your home directory

fixed by #8dee0a8c865b55c251f640130c4c0aa782f290e5
Download build: https://github.com/qaul/qaul.net/releases/tag/v2.0.0-beta.4%2B782-flutter
