### ISSUE TITLE
Android Apk size is too large

### ISSUE THREAD

**Issue by cinorid** [qaul/qaul.net#427]
The size of apk file is too large.
this doc may be useful:
https://github.com/johnthagen/min-sized-rust

**Comment by MathJud** [comment]
### Stats of beta 4 (build 782)

| Binary | size |
|--------|------|
| libqaul.so arm64-v8a | 16 MB |
| libqaul.so armeabi-v7a | 12 MB |
| libqaul.so x86 | 15 MB |
| libqaul.so x86_64 | 16 MB |
| playstore apk download | 16.28 MB |
| sharable unified apk (contains all 4 supported architectures) | 117 MB ||

We are working on optimizing it's size.

**Comment by cinorid** [comment]
It's great.
the previous universal apk file size was about 1GB.

**Comment by MathJud** [comment]
the size of 1GB usually results from a testing APK when built yourself. The release versions should be much smaller.

You can now download the latest universal APK from the github release page.
The apk is signed by google and should be directly installable.
