### ISSUE TITLE
Providing downloadable apk file in release page

### ISSUE THREAD

**Issue by cinorid** [qaul/qaul.net#442]

**Comment by MathJud** [comment]
The github release page now contains the universal APK as downloadable binary. 
This APK works for all devices.

https://github.com/qaul/qaul.net/releases/tag/v2.0.0-beta.6%2B821-flutter

**Comment by cinorid** [comment]
@MathJud 
Please also provide a light APK which target only armeabi-v7a and arm64-v8a.
