### ISSUE TITLE
Background service for syncing messages.

### ISSUE THREAD

**Issue by cinorid** [qaul/qaul.net#484]

**Comment by MathJud** [comment]
To have libqaul running in the background on mobile is an important feature, as it allows the exchange of messages when the app is not in the foreground.

We are researching, how to realize that.
Suggestions are welcome.

**Comment by MathJud** [comment]
Fixed for Android by #554 
It is now published in qaul 2.0.0 beta 15

**Comment by DocSniper** [comment]
How about [UnifiedPush](https://unifiedpush.org/) and [ntfy](https://ntfy.sh/) ?

Edit: I've been using ntfy for quite a while with Element and also FindMyDevice and it works great. But I suspect it will only be useful for server connections.
