### ISSUE TITLE
cmake, Linux: check for additional libraries

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#49]
The following libraries / packages are required and not checked by cmake:

```
bison flex automake
```

**Comment by saces** [comment]
partially solved by 9b4e6add45d851481daafcf3166ef8b039e306f9

Bison and Flex are added as dependency (at least on Linux), they are required by olsr.

Automake is required by portfw wich is planned to be replaced.. I didnt find something easy to copypasta for now.
