### ISSUE TITLE
Naviation Icons not fully visible on Linux

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#536]
The icons in the navigation bar are not fully visible anymore.
Please see the screenshots below.

**Comment by MathJud** [comment]
![Screenshot from 2023-03-04 18-58-42](https://user-images.githubusercontent.com/1871891/222921846-7dedd8bd-0c8d-467f-9927-d8ff53033b4c.png)

**Comment by MathJud** [comment]
![Screenshot from 2023-03-04 18-57-36](https://user-images.githubusercontent.com/1871891/222921860-fef483e5-ebaa-435e-802a-cdaf6217b255.png)

**Comment by brenodt** [comment]
@MathJud Do you feel the sizing of the icons looks ok?
![sample](https://user-images.githubusercontent.com/54450520/223513263-06debd2e-69c5-4546-a7e0-3cd657a8177b.png)

**Comment by MathJud** [comment]
> @MathJud Do you feel the sizing of the icons looks ok? ![sample](https://user-images.githubusercontent.com/54450520/223513263-06debd2e-69c5-4546-a7e0-3cd657a8177b.png)

@brenodt it would be nice to have them a bit bigger
