### ISSUE TITLE
Group Settings Menu not displayed on Desktop

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#540]
On Linux, the `Group Settings` options is not displayed when clicking on the three dots menu in the messenger in a group room.

When clicking on the three dots, `show menu` overlay hint is displayed.

![Screenshot from 2023-03-21 09-24-20](https://user-images.githubusercontent.com/1871891/226552925-4fb76642-495b-4796-bf13-1eb8eae791ca.png)

**Comment by brenodt** [comment]
@MathJud Are there any error logs?
I've attempted replicating the bug, both in Linux & MacOS, with the local user being either Admin or not, but it seems to work fine on my machine:
![context_menu_open](https://user-images.githubusercontent.com/54450520/227035311-ab51921a-fa26-4384-94e0-a06c54987ee7.png)
![settings_page](https://user-images.githubusercontent.com/54450520/227035324-2bba6989-400d-43d4-8e1f-f2fa86ab4d5c.png)

**Comment by MathJud** [comment]
I can see that this bug does not exist, when one opens an already existing group. 

I could replicate this bug, by creating a new group:

- when creating the first new group, it does open, it does not show the settings.
- when creating a further new group, it does not open this group in the window.
