### ISSUE TITLE
Links to v2.0.0-beta.16 releases broken

### ISSUE THREAD

**Issue by Chewie9999** [qaul/qaul.net#575]
All the links to binaries in the "App Installers" section on page https://github.com/qaul/qaul.net/releases/tag/v2.0.0-beta.16 are broken and generate 404s.

**Comment by brenodt** [comment]
Thanks for the feedback!
This was a test release meant for a Android testing workshop. I went ahead and removed it to avoid further confusion.
For the time being, you can refer to the previous release, [v2.0.0-beta.15](https://github.com/qaul/qaul.net/releases/tag/v2.0.0-beta.15).
