### ISSUE TITLE
How to use BLE

### ISSUE THREAD

**Issue by cinorid** [qaul/qaul.net#582]
Hi
I built the application according to the documentation, but I failed to connect two Android devices via Bluetooth and transfer any messages.
Can you provide instructions for testing this.

Thanks

**Comment by MathJud** [comment]
It should work out of the box.
Bluetooth needs to be switched on on both devices.
Just start the app on both devices and they should find each other and display the other user within a few seconds.
If the users meet for the first time it will take a bit longer (about 10-20 seconds).
So far, we tested with devices running Android 13, 12, 11 & 10.

**Comment by MathJud** [comment]
I just updated the build and run documentation to represent the new build procedure.

http://qaul.github.io/qaul.net/#/qaul/flutter/android

**Comment by cinorid** [comment]
> It should work out of the box.
> Bluetooth needs to be switched on on both devices.
> Just start the app on both devices and they should find each other and display the other user within a few seconds.
> If the users meet for the first time it will take a bit longer (about 10-20 seconds).
> So far, we tested with devices running Android 13, 12, 11 & 10.

Thanks for your assistance
I'm using these two Android devices
Xiaomi POCO M5S
SAMSUNG Galaxy tab A 8.0

Screenshots related to Poco device:
![Screenshot_2023-08-05-06-45-22-093_net.qaul.qaul_app.jpg](https://github.com/qaul/qaul.net/assets/10947730/d80c9320-4aea-4452-aa7a-2d502a074fd9)

![Screenshot_2023-08-05-06-44-59-813_com.google.android.permissioncontroller.jpg](https://github.com/qaul/qaul.net/assets/10947730/f69681e2-9853-4ddf-a346-5c12f67fb534)

![Screenshot_2023-08-05-06-48-49-026_com.android.settings.jpg](https://github.com/qaul/qaul.net/assets/10947730/e7c2fbf3-69ba-4922-a009-5e14c422b837)

![Screenshot_2023-08-05-06-45-11-971_com.google.android.permissioncontroller.jpg](https://github.com/qaul/qaul.net/assets/10947730/ab181ac2-f51f-4959-8d49-77b667b13b58)



Screenshots related to Samsung device:

![Screenshot_20230805-074600_064919.jpg](https://github.com/qaul/qaul.net/assets/10947730/66b1905d-7daf-4d34-b2b4-d06c02beeb1d)

![Screenshot_20230805-074800_Settings_064911.jpg](https://github.com/qaul/qaul.net/assets/10947730/baa69a98-0a6d-4815-b4ce-7b9f591ec63b)

![Screenshot_20230805-074654_Permission controller_064917.jpg](https://github.com/qaul/qaul.net/assets/10947730/9c180733-34a6-4b60-961b-209241067793)

![Screenshot_20230805-074702_Permission controller_064915.jpg](https://github.com/qaul/qaul.net/assets/10947730/882d9ba2-b86d-4410-9774-18f1bccd1f1c)

Bluetooth and WiFi is enabled and even Bluetooth is paired on both devices. But unfortunately nothing is sent or received.

**Comment by MathJud** [comment]
After investigating the matter further, the problem seems to be the following: #586

**Comment by MathJud** [comment]
This problem should have been fixed by #586 
Feel free to open this bug again, if the problem stil exists.
The fixed code is now published on android playstore & github release.
