### ISSUE TITLE
Running on Windows 11 only shows a blank window

### ISSUE THREAD

**Issue by MageDelfador** [qaul/qaul.net#645]
version: qaul_installer_2.0.0-rc.1.exe
![11111](https://github.com/user-attachments/assets/6574ba78-ed4b-465b-8683-2d4274cb18fd)
Works fine after creating the folder

**Comment by MathJud** [comment]
fixed by #647

**Comment by MathJud** [comment]
The windows binary on qaul RC1 is fixed now too.
