### ISSUE TITLE
What discussion channels should be created for qaul.net

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#92]
What possibilities should be created to discuss problems, configuration, concepts etc. of qaul.net.
- Mailing list
- Forum
- IRC
- Wiki
- Nothing (github is enough)

Thanks for your thoughts.

**Comment by MathJud** [comment]
I would be in favor of a mailing list.

**Comment by anuvazhayil** [comment]
Is this discussion still open? I have a suggestion to make. How about installing a Phabricator, it can track all tasks and activities. We can also create a thread for open discussion and good interface :D http://phabricator.org/

**Comment by jaromil** [comment]
If needed, we can host the mailinglist on lists.dyne.org: we maintain that already, happy to share.

**Comment by deavmi** [comment]
IRC.

**Comment by deavmi** [comment]
I think IRC and mailing list (I like mailing list the most probably).
